---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-gateway
  labels:
    app: fmstack-nlp
data:
  config.yaml: |
    orchestrator:
      host: "localhost"
      port: 8032
    detectors:
      - name: regex_competitor
        input: true
        output: true
        detector_params:
          regex:    
            - \b(?i:vmware|broadcom|docker|oracle|suse)\b
      - name: hap
        input: true
        output: true
        detector_params: {}
    routes:
      - name: all
        detectors:
          - regex_competitor
          - hap
      - name: hap
        detectors:
          - hap
      - name: passthrough
        detectors:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guardrails-orchestrator-config
data:
  regexDetectorImage: 'quay.io/trustyai/regex-detector:latest'
  vllmGatewayImage: 'quay.io/trustyai/vllm-orchestrator-gateway:latest'
---
apiVersion: v1
kind: Service
metadata:
  name: guardrails-gateway
spec:
  selector:
    app: guardrails-orchestrator
    component: guardrails-orchestrator
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: guardrails-gateway
  labels: {}
spec:
  to:
    kind: Service
    name: guardrails-gateway
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: ''
    destinationCACertificate: ''
  port:
    targetPort: 8090
  alternateBackends: []
---
kind: ConfigMap
apiVersion: v1
metadata:
 name: fms-orchestr8-config-nlp
data:
  config.yaml: |
    chat_generation: 
      service:
        hostname: granite-33-2b-instruct-predictor.trustyai-demo.svc.cluster.local
        port: 8080
    detectors:
      regex_competitor:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      hap: 
        type: text_contents
        service:
          hostname: guardrails-detector-ibm-hap-predictor.trustyai-demo.svc.cluster.local
          port: 8000
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
---
apiVersion: trustyai.opendatahub.io/v1alpha1
kind: GuardrailsOrchestrator
metadata:
  name: guardrails-orchestrator
spec:
  orchestratorConfig: "fms-orchestr8-config-nlp"
  enableGuardrailsGateway: true
  guardrailsGatewayConfig: "fms-orchestr8-config-gateway"
  enableBuiltInDetectors: true
  replicas: 1
---